### ISSUE TITLE
Execution failed for task ':app:bundleReleaseResources'.

### ISSUE THREAD

**Issue by harshalpro224** [ammarahm-ed/react-native-admob-native-ads#109] opened 2020-12-14 09:59 UTC
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/admin12/Downloads/react-native-admob-native-ads-master/example/android/app/build/intermediates/bundle_manifest/release/processReleaseManifest/bundle-manifest/AndroidManifest.xml:13: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by ammarahm-ed** [comment] 2021-01-18 09:50
duplicate of #117

**Closed by ammarahm-ed** 2021-01-18 09:50 UTC
