### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by urunky** [ammarahm-ed/react-native-admob-native-ads#16] opened 2020-04-27 20:32 UTC
First, thank you for your great work!!!!!
I'm very happy to use your libraray. This library is what I'm looking for. 

I'm using your library for my new developing android app. 
I'm using 'FlatList' and using 'renderItem' for rendering NativeAdView.
NativeAdView is top of the list items. total 13 items are rendered.

But the performance is not good as I expected.

So I tested some cases. 
all the results are actual device in debug mode. just after load native ad, no interaction.

device profile : samsung galaxy m20 ( Android 9)
react native : 0.61.5
library version : 0.2.6

1. Not render NativeAd 
UI : 60 / JS: 60 

2. NativeAdView without any children
```javascript
<NativeAdView
     adUnitID="ca-app-pub-3940256099942544/2247696110" // TEST adUnitID
 />
```
UI : 8~35 / JS: 30-35

3. NativeAdView with children
```javascript
<NativeAdView
    adUnitID="ca-app-pub-3940256099942544/2247696110" // TEST adUnitID
>
    <View style={themeStyle.bg}>
         <AdBadge />
          <View>
            <IconView />
            <View>
              <HeadlineView />
              <TaglineView numberOfLines={1} />
              <AdvertiserView />
            </View>
            <CallToActionView />
        </View>
    </View>
</NativeAdView>
``` 
UI : 5 ~ 17 / JS: 8 ~ 20

4. only NativeAdView at App.jsx(root file)
UI : 5 ~ 15 / JS : 9 ~ 12

When using release mode the performance is little bit better but not good. (I guess it's not over 30fps)

did you have  any performance when testing on android devices?

**Comment by ammarahm-ed** [comment] 2020-04-28 09:48
@urunky Thanks for opening this issue, I will look into why there is such performance drop and report back.

**Comment by ammarahm-ed** [comment] 2020-04-28 10:23
Okay so I tested it, I am getting 60fps when there is only one ad in the Flatlist at a time, If i am rendering more than one, the fps drops and that is because you should not render more than one NativeAd at a time. 

With one ad, i am getting 60fps in dev mode with ui components.

**Comment by urunky** [comment] 2020-04-28 18:33
@ammarahm-ed Thanks for fast reply!!

Maybe my explanation was not exact. 
My goal is using 2 native ads, start of list, end of list.
There are always enough items between two nativeads, user can't see more than one nativeAd at a time. I don't know this goal bans the admob nativead banner guides.

Like you said, If I use only one nativead, the performance is not bad(~40fps) in debug mode (because my testing device is very entry model). 

But I'm using two nativead, the fps drops to 5~20 fps. 

I think I'd be better use only one nativead this time, and 

Thanks again for your good lib!!!

**Comment by ammarahm-ed** [comment] 2020-04-28 19:08
@urunky I will look into this to find the reason why the frames are dropping when there are multiple ads in the same screen. its a strange behavior. but until then you can make sure there is only ad rendered in the list at one time.

**Comment by paddy57** [comment] 2020-04-29 10:03
Hello @ammarahm-ed  I'm using Samsung M30 
My NativeAdView have   
```
  CallToActionView,
 MediaView,
  IconView,
  HeadlineView,
  TaglineView,
```

I have a single ad on one screen, 
with video ad units - I'm getting UI 9-15 fps and Js 9-15 
with image ad units -  UI 16-25 fps and Js 16-25 fps

**Comment by ammarahm-ed** [comment] 2020-04-29 10:35
@paddy57 @urunky I am investigating the issue, I hope this will be fixed soon.

**Comment by paddy57** [comment] 2020-04-29 12:46
@ammarahm-ed is there any direction I can look for ? I would like to help in solving this issue

**Comment by ammarahm-ed** [comment] 2020-04-29 15:17
@paddy57 until now I have only been able to improve the performance incrementally at a very small level by removing some nesting of views on native side, but I am still unable to find the exact reason due to which the UI-thread is being blocked. You can look at the code on Native Android side to see if you can find any bottlenecks in code that might be the cause of the issue.

**Comment by ammarahm-ed** [comment] 2020-05-03 13:49
@urunky @paddy57 this has been fixed, will come in 0.2.9 release. I am closing this issue now

**Closed by ammarahm-ed** 2020-05-03 13:49 UTC

**Comment by paddy57** [comment] 2020-07-08 10:45
@ammarahm-ed can you tell me how did you inform the frame rate?

**Comment by ammarahm-ed** [comment] 2020-07-08 10:47
The issue was relatef to a Hack that i was using to make sure views were rendered properly but I realized it was doing more bad than good. You can update to the latest release.
