### ISSUE TITLE
Build failed in ios

### ISSUE THREAD

**Issue by haresh4d** [ammarahm-ed/react-native-admob-native-ads#144] opened 2021-04-01 10:04 UTC
I am using react-native-admob and react-native-admob-native-ads both the library. When I installed this library the build is now failed with following error:

The following build commands failed:
	CompileC /Users/haresh/Library/Developer/Xcode/DerivedData/dkt-hcmkqyitdpvkskbpnimrevfadqpm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-admob-native-ads.build/Objects-normal/x86_64/RNGADNativeViewManager.o /Users/haresh/Development/ReactNative/citizen_au/node_modules/react-native-admob-native-ads/ios/RNGADNativeViewManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by konradgalczynski07** [comment] 2021-04-20 09:57
Same with combination `@react-native-firebase/admob` and `react-native-admob-native-ads`

**Comment by haresh4d** [comment] 2021-04-20 11:48
Use 0.3.9 version of native library. It will work

**Comment by ammarahm-ed** [comment] 2021-05-07 10:02
Fixed on master

**Closed by ammarahm-ed** 2021-05-07 10:02 UTC

**Comment by heinsaar** [comment] 2021-05-11 15:40
I'm getting the same exact same error with all the latest code. @ammarahm-ed Could you please specify which fix are you referring to?

**Comment by ammarahm-ed** [comment] 2021-05-11 17:47
> I'm getting the same exact same error with all the latest code. @ammarahm-ed Could you please specify which fix on master are you referring to?  

Use the latest version of library.

**Comment by heinsaar** [comment] 2021-05-11 19:02
> Use the latest version of library.

I'm using version 0.4.1 alongside react-native 0.64 as in my package.json:
```

    "react-native": "0.64.0",
    "react-native-admob-native-ads": "^0.4.1",

```
Did you mean 0.4.1 as the latest version? Is it compatible with react-native 0.64.0?

Just to try everything I tried downgrading to 0.3.9 and forcing dependencies during installation, but that didn't work either.

The error I receive is this (3 failures, as it says below - might be exactly the same as in the issue description):

> ** BUILD FAILED **
> The following build commands failed:
> CompileC .../Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-admob-native-ads.build/Objects-normal/x86_64/RNGADNativeViewManager.o .../node_modules/react-native-admob-native-ads/ios/RNGADNativeViewManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> 
> CompileC .../Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-admob-native-ads.build/Objects-normal/x86_64/RNGADNativeView.o .../node_modules/react-native-admob-native-ads/ios/RNGADNativeView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> 
> CompileC .../Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-admob-native-ads.build/Objects-normal/x86_64/RNAdmobNativeAdsManager.o .../node_modules/react-native-admob-native-ads/ios/RNAdmobNativeAdsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> 
> (3 failures)

**Comment by heinsaar** [comment] 2021-05-12 07:35
Ok so I did some cleaning of the iOS build and now my build fails are down to just one (the first one for **react-native-admob-native-ads.build/Objects-normal/x86_64/RNGADNativeViewManager.o**, which is also the only one for issue creator I think).

It looks like this might be just a matter of proper cleaning so the linking and dependencies hook into each other correctly, but it'd be nice to have the steps documented somewhere (in addition to in this thread) as probably I'm not the only one new to React Native / iOS development who might be interested in trying out this library. Right now I'm going over anything I can find on the web with "react native The following build commands failed: CompileC" and trying to come up with with the right cleaning so the only remaining failure also fixes.

Otherwise this is a great lib by the way @ammarahm-ed, thank you.

**Comment by ammarahm-ed** [comment] 2021-05-12 08:18
> Ok so I did some cleaning of the iOS build and now my build fails are down to just one (first in the list above, the one for **react-native-admob-native-ads.build/Objects-normal/x86_64/RNGADNativeViewManager.o**, which is also the only one for issue creator I think).
> 
> It looks like this might be just a matter of proper cleaning so the linking and dependencies hook into each other correctly, but it'd be nice to have the steps documented somewhere (in addition to in this thread) as probably I'm not the only one new to React Native / iOS development who might be interested in trying out this library. Right now I'm going over anything I can find on the web with "react native The following build commands failed: CompileC" and trying to come up with with the right cleaning so the only remaining failure also fixes.
> 
> Otherwise this is a great lib by the way @ammarahm-ed, thank you.

You should open xcode and build your project there so you can see what is actually causing the build to fail. What version good "Good Mobile Ads Sdk" are you using. It should be `7.66` i think same as rn firebase. The log you provided don't help since they do not show where or what symbols are missing.

**Comment by heinsaar** [comment] 2021-05-12 08:35
> You should open xcode and build your project there so you can see what is actually causing the build to fail. What version good "Good Mobile Ads Sdk" are you using. It should be 7.66 i think same as rn firebase. The log you provided don't help since they do not show where or what symbols are missing.

The exact line causing the problem is this:

> .../node_modules/react-native-admob-native-ads/ios/RNAdmobNativeAdsManager.m:38:96: error: use of undeclared identifier 'kDFPSimulatorID'
>         NSArray *testDevices = RNAdMobProcessTestDevices([config valueForKey:@"testDeviceIds"],kDFPSimulatorID);
>                                                                                                ^
> 1 error generated.

The “pod install” log shows:

> Installing Google-Mobile-Ads-SDK (8.5.0)

Is 8.5.0 too high?

**Comment by heinsaar** [comment] 2021-05-12 08:57
I just tried setting in Podfile the version you mentioned:

> pod 'Google-Mobile-Ads-SDK', '7.66'

Then in /ios dir I deleted Pods dir and reran `pod install`, but now it’s messing up other dependencies, I’m getting this error:

> [!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
>   In Podfile:
>     Google-Mobile-Ads-SDK (= 7.66)
> 
>     react-native-admob-native-ads (from `../node_modules/react-native-admob-native-ads`) was resolved to 0.4.1, which depends on
>       GoogleMobileAdsMediationFacebook was resolved to 6.4.1.0, which depends on
>         Google-Mobile-Ads-SDK (>= 8.4.0)

It looks to me that version 0.4.1 links to Facebook's mediation... which ends up dissatisfied with  Google-Mobile-Ads-SDK version 7.66, wants at least 8.4.0?

**Comment by felire** [comment] 2021-10-21 18:34
@ammarahm-ed Could you re open this? I am getting `Could not build module 'React'` on `RNGADNativeViewManager` file

**Comment by ammarahm-ed** [comment] 2021-10-22 04:37
What is your RN version @felire

**Comment by harisraza123** [comment] 2022-02-22 23:43
Hi @ammarahm-ed I'm having the same issue as @felire 
My RN version is `0.61.2`.
