### ISSUE TITLE
Task :app:processDebugResources FAILED

### ISSUE THREAD

**Issue by viveKing21** [ammarahm-ed/react-native-admob-native-ads#105] opened 2020-12-06 11:34 UTC
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
208 actionable tasks: 19 executed, 189 up-to-date
Note: E:\ReactNative\bhajanbook\node_modules\react-native-admob-native-ads\android\src\main\java\com\ammarahmed\rnadmob\nativeads\RNNativeAdWrapper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\sharm\.gradle\caches\transforms-2\files-2.1\23e9bd4ea99c76ba7f1eb83035085b4b\play-services-ads-lite-19.6.0\AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

im getting this error after install this package, when im running this command 'react-native run-android'
im getting this issue with this version of react-native-admod-native-ads  (0.3.9)
but its woring on 0.3.6

**Comment by faz1993** [comment] 2020-12-08 02:04
same

**Comment by ammarahm-ed** [comment] 2021-01-18 09:48
duplicate of #117

**Closed by ammarahm-ed** 2021-01-18 09:48 UTC
